version: '3'

services:
  db:
    image: 'postgres'
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'

volumes:
  db-data:
